model_names = [
    'antimicrobial',
    'antimicrobial_route',
    'clinical_advice_reason_for_interaction',
    'condition',
    'destination',
    'hospital',
    'microbiology_organism',
    'travel_reason',

    # Types of microbiology test
    'micro_test_c_difficile',
    'micro_test_csf_pcr',
    'micro_test_ebv_serology',
    'micro_test_hepititis_b_serology',
    'micro_test_hiv',
    'micro_test_leishmaniasis_pcr',
    'micro_test_mcs',
    'micro_test_other',
    'micro_test_parasitaemia',
    'micro_test_respiratory_virus_pcr',
    'micro_test_serology',
    'micro_test_single_igg_test',
    'micro_test_single_test_pos_neg',
    'micro_test_single_test_pos_neg_equiv',
    'micro_test_stool_parasitology_pcr',
    'micro_test_stool_pcr',
    'micro_test_swab_pcr',
    'micro_test_syphilis_serology',
    'micro_test_viral_load',
]
