# Generated by Django 2.0.9 on 2018-11-02 16:54

from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20181102_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
            bases=(opal.models.UpdatesFromDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GetterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=(opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SerialisableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=200, null=True)),
                ('hatty_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('hatty_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.Hat')),
            ],
            bases=(opal.models.SerialisableFields, models.Model),
        ),
        migrations.CreateModel(
            name='UpdatableModelInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(blank=True, max_length=200, null=True)),
                ('bar', models.CharField(blank=True, max_length=200, null=True)),
                ('pid', models.CharField(blank=True, max_length=200, null=True)),
                ('hatty_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('hatty_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.Hat')),
            ],
            bases=(opal.models.UpdatesFromDictMixin, models.Model),
        ),
    ]
