# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inpatientadmission',
            options={'verbose_name': 'Inpatient Admissions'},
        ),
        migrations.AlterModelOptions(
            name='tagging',
            options={'verbose_name': 'Teams'},
        ),
    ]
