# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-30 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0035_auto_20180713_1039'),
        ('opal', '0035_auto_20180806_1150'),
    ]

    operations = [
    ]
