# Generated by Django 2.0.13 on 2019-11-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0038_auto_20191107_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
