# Generated by Django 2.0.13 on 2019-11-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0039_auto_20191129_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactNumber',
        ),
    ]
