# Generated by Django 2.0.13 on 2019-11-29 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referencedata', '__first__'),
        ('opal', '0041_auto_20191129_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('value', models.CharField(help_text='The actual identifier string', max_length=255)),
                ('id_type', models.CharField(help_text='Description of ID', max_length=255)),
                ('use', models.CharField(choices=[('Usual', 'Usual'), ('Official', 'Official'), ('Temp', 'Temp'), ('Old', 'Old')], help_text='How should we use this ID', max_length=255)),
                ('assigner', models.CharField(help_text='Organization that issued this ID', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opal_identifier_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('name_text', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Emergency Contact', 'Emergency Contact'), ('Employer', 'Employer'), ('Federal Agency', 'Federal Agency'), ('Insurance Company', 'Insurance Company'), ('Next-of-Kin', 'Next-of-Kin'), ('State Agency', 'State Agency')], max_length=255, null=True)),
                ('telecom', models.TextField(blank=True, help_text='The phone, email or other details for this contact', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opal_patientcontact_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PatientContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('system', models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Fax', 'Fax'), ('Email', 'Email'), ('Pager', 'Pager'), ('URL', 'URL'), ('SMS', 'SMS'), ('Other', 'Other')], max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('use', models.CharField(blank=True, choices=[('Home', 'Home'), ('Work', 'Work'), ('Temp', 'Temp'), ('Old', 'Old'), ('Mobile', 'Mobile')], max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opal_patientcontactdetail_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Antimicrobial',
        ),
        migrations.DeleteModel(
            name='Antimicrobial_adverse_event',
        ),
        migrations.DeleteModel(
            name='Antimicrobial_frequency',
        ),
        migrations.DeleteModel(
            name='Antimicrobial_route',
        ),
        migrations.DeleteModel(
            name='Clinical_advice_reason_for_interaction',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='Drugfreq',
        ),
        migrations.DeleteModel(
            name='Drugroute',
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.RemoveField(
            model_name='inpatientadmission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inpatientadmission',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='inpatientadmission',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='MaritalStatus',
        ),
        migrations.DeleteModel(
            name='PatientConsultationReasonForInteraction',
        ),
        migrations.DeleteModel(
            name='ReferralOrganisation',
        ),
        migrations.DeleteModel(
            name='ReferralType',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.DeleteModel(
            name='Travel_reason',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AddField(
            model_name='patient',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this patient record is in active use'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_text',
            field=models.TextField(blank=True, help_text='Text representation of the address', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_place_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referencedata.Country'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_place_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased',
            field=models.BooleanField(default=False, help_text='This field will be True if the patient is deceased.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time of death'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referencedata.Ethnicity'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_name',
            field=models.CharField(blank=True, help_text="Often called 'Surname'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='given_names',
            field=models.CharField(blank=True, help_text='Often called first. Also includes middle', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referencedata.MaritalStatus'),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_prefex',
            field=models.CharField(blank=True, help_text='Parts that come before the name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_suffix',
            field=models.CharField(blank=True, help_text='Parts that come after the name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='InpatientAdmission',
        ),
        migrations.AddField(
            model_name='patientcontactdetail',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient'),
        ),
        migrations.AddField(
            model_name='patientcontactdetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_opal_patientcontactdetail_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient'),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_opal_patientcontact_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identifier',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_opal_identifier_subrecords', to=settings.AUTH_USER_MODEL),
        ),
    ]
